In [1]:
import numpy as np

#### Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [4]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1, 2, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size

6

##### Creating Numpy Arrays from Scratch
Zeros, ones, full, arange, linspace

In [15]:
np.zeros([2,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

##### `random`

In [23]:
np.random.random((4,4))

array([[0.20935978, 0.41366177, 0.73298207, 0.3025462 ],
       [0.59650018, 0.33683172, 0.91327016, 0.15602754],
       [0.38740882, 0.1090434 , 0.40155195, 0.68847334],
       [0.32524321, 0.02012879, 0.86317747, 0.92456563]])

In [26]:
# Seed for reproducibility
np.random.seed(0)

np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [27]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [32]:
np.random.seed(0)
np.random.randint(0,10,(2,2))

array([[5, 0],
       [3, 3]])

##### Array Indexing & Slicing
##### One-dimensional subarray

In [33]:
x1 = np.random.randint(20, size=6)

In [34]:
x1

array([ 7,  9, 19, 18,  4,  6])

In [37]:
x1[4], x1[0], x1[-1]

(4, 7, 6)

##### Multi-dimensional array

In [38]:
x2 = np.random.randint(10, size= (3,4))

In [39]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [40]:
x2[1,2]

8

In [41]:
x2[1,2] = 6

In [42]:
x2

array([[8, 8, 1, 6],
       [7, 7, 6, 1],
       [5, 9, 8, 9]])

###### Slicing:

In [43]:
x1

array([ 7,  9, 19, 18,  4,  6])

In [44]:
x1[0:3]

array([ 7,  9, 19])

In [45]:
x1[2:4]

array([19, 18])

In [46]:
x1[::2]

array([ 7, 19,  4])

In [47]:
x2

array([[8, 8, 1, 6],
       [7, 7, 6, 1],
       [5, 9, 8, 9]])

In [48]:
# 2 dòng đầu, 3 cột
x2[:2,:3]

array([[8, 8, 1],
       [7, 7, 6]])

In [49]:
x2[:, :2]

array([[8, 8],
       [7, 7],
       [5, 9]])

##### Reshaping of Arrays & Transpose

In [50]:
grid = np.arange(1,10)
grid.shape

(9,)

In [51]:
grid.reshape

<function ndarray.reshape>

In [52]:
x = np.array([1, 2, 3])

In [53]:
x.shape

(3,)

In [55]:
x.reshape((1,3)).shape

(1, 3)